# Generated by Django 4.1.5 on 2024-04-12 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostTableAll',
            fields=[
                ('p_mid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('p_auther', models.CharField(blank=True, max_length=256, null=True)),
                ('p_txt', models.CharField(blank=True, max_length=6144, null=True)),
                ('p_transmit', models.IntegerField(blank=True, null=True)),
                ('p_comment', models.IntegerField(blank=True, null=True)),
                ('p_like', models.IntegerField(blank=True, null=True)),
                ('p_title', models.CharField(blank=True, max_length=256, null=True)),
                ('p_uid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_table_all',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopicTable',
            fields=[
                ('t_title', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('t_label', models.CharField(blank=True, max_length=256, null=True)),
                ('t_time', models.CharField(blank=True, max_length=256, null=True)),
                ('t_host', models.CharField(blank=True, max_length=256, null=True)),
                ('t_continue', models.IntegerField(blank=True, null=True)),
                ('t_sort', models.IntegerField(blank=True, null=True)),
                ('t_hot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopicTableAll',
            fields=[
                ('t_index', models.AutoField(primary_key=True, serialize=False)),
                ('t_title', models.CharField(blank=True, max_length=256, null=True)),
                ('t_label', models.CharField(blank=True, max_length=256, null=True)),
                ('t_time', models.CharField(blank=True, max_length=256, null=True)),
                ('t_host', models.CharField(blank=True, max_length=256, null=True)),
                ('t_continue', models.IntegerField(blank=True, null=True)),
                ('t_sort', models.IntegerField(blank=True, null=True)),
                ('t_hot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic_table_all',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('u_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=256)),
                ('u_password', models.CharField(max_length=20)),
                ('u_sex', models.IntegerField(blank=True, null=True)),
                ('u_birth', models.DateField(blank=True, null=True)),
                ('u_txt', models.CharField(blank=True, max_length=1024, null=True)),
                ('u_admin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('p_mid', models.OneToOneField(db_column='p_mid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.posttableall')),
                ('p_auther', models.CharField(blank=True, max_length=256, null=True)),
                ('p_txt', models.CharField(blank=True, max_length=6144, null=True)),
                ('p_transmit', models.IntegerField(blank=True, null=True)),
                ('p_comment', models.IntegerField(blank=True, null=True)),
                ('p_like', models.IntegerField(blank=True, null=True)),
                ('p_uid', models.BigIntegerField(blank=True, null=True)),
                ('p_birthday', models.CharField(blank=True, max_length=256, null=True)),
                ('p_constellation', models.CharField(blank=True, max_length=256, null=True)),
                ('p_created_at', models.CharField(blank=True, max_length=256, null=True)),
                ('p_gender', models.IntegerField(blank=True, null=True)),
                ('p_location', models.CharField(blank=True, max_length=256, null=True)),
                ('p_audence_id', models.CharField(blank=True, max_length=2048, null=True)),
                ('t_title', models.ForeignKey(blank=True, db_column='t_title', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.topictable')),
            ],
            options={
                'db_table': 'post_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('c_index', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_audience_id', models.BigIntegerField(blank=True, null=True)),
                ('c_like_counts', models.IntegerField(blank=True, null=True)),
                ('c_screen_name', models.CharField(blank=True, max_length=256, null=True)),
                ('c_location', models.CharField(blank=True, max_length=256, null=True)),
                ('c_gender', models.IntegerField(blank=True, null=True)),
                ('c_followers_count', models.IntegerField(blank=True, null=True)),
                ('c_friends_count', models.IntegerField(blank=True, null=True)),
                ('c_statuses_count', models.IntegerField(blank=True, null=True)),
                ('c_text_raw', models.CharField(blank=True, max_length=2048, null=True)),
                ('c_mid', models.ForeignKey(blank=True, db_column='c_mid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.posttable')),
            ],
            options={
                'db_table': 'comment_table',
                'managed': True,
            },
        ),
    ]
