# Generated by Django 4.1.5 on 2024-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookiesTable',
            fields=[
                ('co_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('co_cookie', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'cookies_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimePostTableAll',
            fields=[
                ('tp_mid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tp_auther', models.CharField(blank=True, max_length=256, null=True)),
                ('tp_txt', models.CharField(blank=True, max_length=6144, null=True)),
                ('tp_transmit', models.IntegerField(blank=True, null=True)),
                ('tp_comment', models.IntegerField(blank=True, null=True)),
                ('tp_like', models.IntegerField(blank=True, null=True)),
                ('tp_title', models.CharField(blank=True, max_length=256, null=True)),
                ('tp_uid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_post_table_all',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeTitleTable',
            fields=[
                ('ti_title', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('ti_label', models.CharField(blank=True, max_length=256, null=True)),
                ('ti_hot', models.IntegerField(blank=True, null=True)),
                ('ti_time', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'time_title_table',
                'managed': True,
            },
        ),
    ]
